backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
media_folder: "assets/img/master" # Where Media files will be stored in the repo
public_folder: "assets/img/master" # The src attribute for uploaded media will begin with /assets/img/master

collections:
  - name: "Home" # Used in routes, e.g., /admin/collections/blog
    label: "Home" # Used in the UI
    folder: "_home" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "/" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "Sunday" # Used in routes, e.g., /admin/collections/blog
    label: "Sunday" # Used in the UI
    folder: "_sunday" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "/sunday" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter

  - name: "Media" # Used in routes, e.g., /admin/collections/blog
    label: "Media" # Used in the UI
    folder: "_media" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "/media" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter

  - name: "Docs" # Used in routes, e.g., /admin/collections/blog
    label: "Docs" # Used in the UI
    folder: "_docs" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "/docs" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter

