<?php include("/home/ceclee/public_html/php/sermons/include.php"); ?>

<div class="flex-row">
  <a class="flex-small" target="_blank" href="https://podcasts.apple.com/us/podcast/city-evangelical-church-sermons/id1537249782" style="background-image: url({% include svg/apple-podcast.svg %})">Listen on Apple Podcasts</a>
  <a class="flex-small" target="_blank" href="https://music.amazon.co.uk/podcasts/cfd1efb8-db38-4a35-a90a-cc20787b6fd7/City-Evangelical-Church-Sermons" style="background-color: #000000;background-image: url(https://sermons.cecleeds.co.uk/img/Podcast.png);background-repeat: no-repeat;background-size: 1533px 28px;border-radius: 5px;text-indent: -9000px;background-position: -1375px 7px;height: 40px;width: 172px; margin: 5px 10px">Listen on Amazon Music</a>
  <a class="flex-small" target="_blank" href="https://www.google.com/podcasts?feed=aHR0cHM6Ly9jZWNsZWVkcy5jby51ay9zZXJtb25zLnBocA%3D%3D" style="background-color: #000000; background-image: url(https://sermons.cecleeds.co.uk/img/Podcast.png); background-repeat: no-repeat; background-size: 1533px 28px; border-radius: 5px; text-indent: -9000px; background-position: -468px 7px; height: 40px; width: 172px; margin: 5px 10px">Listen on Google Podcasts</a>
  <a class="flex-small" target="_blank" href="https://open.spotify.com/show/7mWlXxRZD74wuyfJzAYMFf" style="background-color: #000000; background-image: url(https://sermons.cecleeds.co.uk/img/Podcast.png); background-repeat: no-repeat; background-size: 1533px 28px; border-radius: 5px; text-indent: -9000px; background-position: -182px 7px; height: 40px; width: 106px; margin: 5px 10px">Listen on Spotify</a>
  <a class="flex-small" target="_blank" href="https://cecleeds.co.uk/sermons.php" style="background-color: #000000; background-image: url(https://sermons.cecleeds.co.uk/img/Podcast.png); background-repeat: no-repeat; background-size: 1533px 28px; border-radius: 5px; text-indent: -9000px; background-position: -317px 7px; height: 40px; width: 121px; margin: 5px 10px">RSS Feed</a>
</div>
