name: pull request on gemfile update
on:
  push:
    paths:
      - 'Gemfile'

jobs:
  bundle-update:
    name: bundle update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: work around permission issue
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: pull request on bundle update
        uses: woodcock3/pull-request-on-bundle-update@v1.0.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          git_user_name: ${{ secrets.HUB_USER }}
          git_email: ${{ secrets.HUB_EMAIL }}
          bundler_version: ## 2.2.4 optional
