name: pull request on npm update
on:
  push:
    paths:
      - 'Npm.txt'

jobs:
  npm-update:
    name: npm update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm init -y
      - run: npm install
      - name: pull request on npm update
        uses: woodcock3/pull-request-on-bundle-update@v1.0.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          git_user_name: ${{ secrets.HUB_USER }}
          git_email: ${{ secrets.HUB_EMAIL }}
